services:
  - type: web
    name: instagram-poster
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    runtime: python3.11
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
